In [10]:
import numpy as np
np.arange(12, -1, -1)

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [23]:
new_matrix = np.diag(np.arange(9, -1, -1), k = 0)
print(new_matrix)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [22]:
np.trace(new_matrix)

45

In [25]:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 0, 4]  ] )
b = np.array( [4, 12, -3] )

from numpy import linalg
linalg.solve(a, b)

array([-1.56,  4.52,  1.2 ])

In [26]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [43]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])


def cosine( users_stats, next_user_stats  ):
   
    aLength = np.linalg.norm( users_stats )
    bLength = np.linalg.norm( next_user_stats )
    
    return np.dot( users_stats, next_user_stats ) / ( aLength * bLength )
cosines = cosine(users_stats, next_user_stats )
my_max = np.amax(cosines)
closest_users_index = np.argmax(cosines)
print(cosines)
print(closest_users_index)
# Что нужно было использовать, чтобы вернуть индексы двух пользователей? Это пользоватетели с индексами 1 и 3.

[0.04688072 0.23440362 0.09376145 0.23440362 0.09376145 0.
 0.         0.14064217 0.         0.        ]
1
